# Generated by Django 3.1.5 on 2021-01-18 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_web', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_web.blog')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_web.tag')),
            ],
        ),
    ]
